# Generated by Django 3.1.5 on 2021-01-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll', models.CharField(default='', max_length=50, unique=True, verbose_name='Roll')),
                ('Name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('Maths', models.IntegerField(default=0, verbose_name='Maths')),
                ('Physics', models.IntegerField(default=0, verbose_name='Physics')),
                ('Chemistry', models.IntegerField(default=0, verbose_name='Chemistry')),
                ('Total', models.IntegerField(default=0, verbose_name='Total')),
                ('Percentage', models.IntegerField(default=0, verbose_name='Percentage')),
            ],
        ),
    ]
