# Generated by Django 3.1.5 on 2021-01-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='Percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Percentage'),
        ),
    ]
